/**
 * Dev server: reads src/multibuffer/ source files, generates a sources module,
 * builds demo.ts, and serves on localhost.
 */

import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const demoDir = import.meta.dir;
const srcDir = join(demoDir, "../src/multibuffer");

// 1. Read all .ts source files and generate sources.ts
const sourceFiles = readdirSync(srcDir)
  .filter((f) => f.endsWith(".ts"))
  .sort();

let generated = "// Auto-generated by serve.ts — do not edit\n";
generated += "export const sources: { path: string; content: string }[] = [\n";

for (const file of sourceFiles) {
  const content = readFileSync(join(srcDir, file), "utf-8");
  const escaped = JSON.stringify(content);
  generated += `  { path: "src/multibuffer/${file}", content: ${escaped} },\n`;
}

generated += "];\n";

writeFileSync(join(demoDir, "sources.gen.ts"), generated);
console.log(`Generated sources.gen.ts with ${sourceFiles.length} files.`);

// 2. Build the demo bundle
const buildResult = await Bun.build({
  entrypoints: [join(demoDir, "demo.ts")],
  outdir: join(demoDir, "dist"),
  target: "browser",
  format: "esm",
});

if (!buildResult.success) {
  console.error("Build failed:");
  for (const log of buildResult.logs) {
    console.error(log);
  }
  process.exit(1);
}

console.log("Build successful.");

// 3. Serve
const PORT = 3000;

Bun.serve({
  port: PORT,
  fetch(req) {
    const url = new URL(req.url);
    let path = url.pathname;
    if (path === "/") path = "/index.html";

    const filePath = join(demoDir, path);
    try {
      const file = Bun.file(filePath);
      return new Response(file);
    } catch {
      return new Response("Not found", { status: 404 });
    }
  },
});

console.log(`Demo server running at http://localhost:${PORT}`);
