/**
 * Dev server: reads src/multibuffer/ source files, generates a sources module,
 * builds demo.ts, and serves on localhost.
 */

import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const demoDir = import.meta.dir;
const srcDir = join(demoDir, "../src/multibuffer");
const fixturesDir = join(demoDir, "fixtures");

// 1. Read source files and fixtures, generate sources.ts
function readDir(dir: string, prefix: string): { path: string; content: string }[] {
  return readdirSync(dir)
    .filter((f) => f.endsWith(".ts"))
    .sort()
    .map((f) => ({
      path: `${prefix}${f}`,
      content: readFileSync(join(dir, f), "utf-8"),
    }));
}

const allSources = [
  ...readDir(srcDir, "src/multibuffer/"),
  ...readDir(fixturesDir, "demo/fixtures/"),
];

let generated = "// Auto-generated by serve.ts — do not edit\n";
generated += "export const sources: { path: string; content: string }[] = [\n";

for (const src of allSources) {
  generated += `  { path: ${JSON.stringify(src.path)}, content: ${JSON.stringify(src.content)} },\n`;
}

generated += "];\n";

writeFileSync(join(demoDir, "sources.gen.ts"), generated);
console.log(`Generated sources.gen.ts with ${allSources.length} files.`);

// 2. Build the demo bundle
const buildResult = await Bun.build({
  entrypoints: [join(demoDir, "demo.ts")],
  outdir: join(demoDir, "dist"),
  target: "browser",
  format: "esm",
});

if (!buildResult.success) {
  console.error("Build failed:");
  for (const log of buildResult.logs) {
    console.error(log);
  }
  process.exit(1);
}

console.log("Build successful.");

// 3. Serve
const PORT = 3000;

Bun.serve({
  port: PORT,
  fetch(req) {
    const url = new URL(req.url);
    let path = url.pathname;
    if (path === "/") path = "/index.html";

    const filePath = join(demoDir, path);
    try {
      const file = Bun.file(filePath);
      return new Response(file);
    } catch {
      return new Response("Not found", { status: 404 });
    }
  },
});

console.log(`Demo server running at http://localhost:${PORT}`);
