/**
 * Dev server: reads src/multibuffer/ source files, generates a sources module,
 * builds demo.ts, and serves on localhost.
 */

import { copyFileSync, existsSync, mkdirSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const demoDir = import.meta.dir;
const srcDir = join(demoDir, "../src/multibuffer");
const fixturesDir = join(demoDir, "fixtures");
const nodeModules = join(demoDir, "../node_modules");

// 1. Read source files and fixtures, generate sources.ts
function readDir(dir: string, prefix: string): { path: string; content: string }[] {
  return readdirSync(dir)
    .filter((f) => f.endsWith(".ts"))
    .sort()
    .map((f) => ({
      path: `${prefix}${f}`,
      content: readFileSync(join(dir, f), "utf-8"),
    }));
}

const allSources = [
  ...readDir(srcDir, "src/multibuffer/"),
  ...readDir(fixturesDir, "demo/fixtures/"),
];

let generated = "// Auto-generated by serve.ts — do not edit\n";
generated += "export const sources: { path: string; content: string }[] = [\n";

for (const src of allSources) {
  generated += `  { path: ${JSON.stringify(src.path)}, content: ${JSON.stringify(src.content)} },\n`;
}

generated += "];\n";

writeFileSync(join(demoDir, "sources.gen.ts"), generated);
console.log(`Generated sources.gen.ts with ${allSources.length} files.`);

// 2. Copy WASM files for tree-sitter
const wasmDir = join(demoDir, "wasm");
if (!existsSync(wasmDir)) mkdirSync(wasmDir);

const treeSitterWasm = join(nodeModules, "web-tree-sitter/web-tree-sitter.wasm");
const tsGrammarWasm = join(nodeModules, "tree-sitter-typescript/tree-sitter-typescript.wasm");

if (existsSync(treeSitterWasm)) {
  copyFileSync(treeSitterWasm, join(wasmDir, "tree-sitter.wasm"));
  console.log("Copied tree-sitter.wasm");
}
if (existsSync(tsGrammarWasm)) {
  copyFileSync(tsGrammarWasm, join(wasmDir, "tree-sitter-typescript.wasm"));
  console.log("Copied tree-sitter-typescript.wasm");
}

// Also copy the web-tree-sitter browser JS
const treeSitterJs = join(nodeModules, "web-tree-sitter/web-tree-sitter.js");
if (existsSync(treeSitterJs)) {
  copyFileSync(treeSitterJs, join(wasmDir, "web-tree-sitter.js"));
}

// 3. Build the demo bundle (exclude web-tree-sitter — loaded via script tag)
const buildResult = await Bun.build({
  entrypoints: [join(demoDir, "demo.ts")],
  outdir: join(demoDir, "dist"),
  target: "browser",
  format: "esm",
  external: ["web-tree-sitter"],
});

if (!buildResult.success) {
  console.error("Build failed:");
  for (const log of buildResult.logs) {
    console.error(log);
  }
  process.exit(1);
}

console.log("Build successful.");

// 3. Serve
const PORT = 3000;

Bun.serve({
  port: PORT,
  fetch(req) {
    const url = new URL(req.url);
    let path = url.pathname;
    if (path === "/") path = "/index.html";

    const filePath = join(demoDir, path);
    try {
      const file = Bun.file(filePath);
      return new Response(file);
    } catch {
      return new Response("Not found", { status: 404 });
    }
  },
});

console.log(`Demo server running at http://localhost:${PORT}`);
