/**
 * Static build: generates a self-contained _site/ directory
 * suitable for GitHub Pages or any static host.
 *
 * Usage: bun run demo/build.ts
 */

import {
  copyFileSync,
  existsSync,
  mkdirSync,
  readdirSync,
  readFileSync,
  writeFileSync,
} from "node:fs";
import { join } from "node:path";

const rootDir = join(import.meta.dir, "..");
const demoDir = import.meta.dir;
const srcDir = join(rootDir, "src/multibuffer");
const fixturesDir = join(demoDir, "fixtures");
const nodeModules = join(rootDir, "node_modules");
const outDir = join(rootDir, "_site");

// --- helpers ---

function ensureDir(dir: string) {
  if (!existsSync(dir)) mkdirSync(dir, { recursive: true });
}

function readTsFiles(
  dir: string,
  prefix: string,
): { path: string; content: string }[] {
  return readdirSync(dir)
    .filter((f) => f.endsWith(".ts"))
    .sort()
    .map((f) => ({
      path: `${prefix}${f}`,
      content: readFileSync(join(dir, f), "utf-8"),
    }));
}

// --- 1. Generate sources.gen.ts ---

const allSources = [
  ...readTsFiles(srcDir, "src/multibuffer/"),
  ...readTsFiles(fixturesDir, "demo/fixtures/"),
];

let generated = "// Auto-generated by build.ts — do not edit\n";
generated += "export const sources: { path: string; content: string }[] = [\n";
for (const src of allSources) {
  generated += `  { path: ${JSON.stringify(src.path)}, content: ${JSON.stringify(src.content)} },\n`;
}
generated += "];\n";

writeFileSync(join(demoDir, "sources.gen.ts"), generated);
console.log(`Generated sources.gen.ts with ${allSources.length} files.`);

// --- 2. Copy WASM files ---

const wasmSrc = {
  "tree-sitter.wasm": join(
    nodeModules,
    "web-tree-sitter/web-tree-sitter.wasm",
  ),
  "tree-sitter-typescript.wasm": join(
    nodeModules,
    "tree-sitter-typescript/tree-sitter-typescript.wasm",
  ),
  "web-tree-sitter.js": join(
    nodeModules,
    "web-tree-sitter/web-tree-sitter.js",
  ),
};

const wasmStaging = join(demoDir, "wasm");
ensureDir(wasmStaging);

for (const [name, src] of Object.entries(wasmSrc)) {
  if (existsSync(src)) {
    copyFileSync(src, join(wasmStaging, name));
    console.log(`Copied ${name}`);
  } else {
    console.warn(`Warning: ${src} not found`);
  }
}

// --- 3. Bundle demo.ts ---

const buildResult = await Bun.build({
  entrypoints: [join(demoDir, "demo.ts")],
  outdir: join(demoDir, "dist"),
  target: "browser",
  format: "esm",
  external: ["web-tree-sitter"],
});

if (!buildResult.success) {
  console.error("Build failed:");
  for (const log of buildResult.logs) {
    console.error(log);
  }
  process.exit(1);
}

console.log("Bundle built.");

// --- 4. Assemble _site/ ---

ensureDir(outDir);
ensureDir(join(outDir, "dist"));
ensureDir(join(outDir, "wasm"));

copyFileSync(join(demoDir, "index.html"), join(outDir, "index.html"));
copyFileSync(join(demoDir, "dist/demo.js"), join(outDir, "dist/demo.js"));

for (const name of Object.keys(wasmSrc)) {
  const src = join(wasmStaging, name);
  if (existsSync(src)) {
    copyFileSync(src, join(outDir, "wasm", name));
  }
}

console.log(`Static site written to ${outDir}`);
